- .github/workflows/lint.yml
- .golangci.yml
- editor.go
- editor_test.go
- err.go
- examples/clone_vs_add_hook/demo.go
- manager.go
- map.go
- perf.go
- probe.go
- selectors.go
- syscalls.go
- utils.go
Adds golangci-lint action to run on all pushes
Better CI
> Add golangci-lint action

- go.mod
- go.sum
This PR updates the Cilium library.
Keep the `ebpf-manager` up to date with the latest changes from `cilium/ebpf`.
> Update cilium library

- manager.go
Ports fixes from https://github.com/DataDog/ebpf/pull/58 and https://github.com/DataDog/ebpf/pull/59
> Port fixes from DataDog/ebpf

- manager.go
This PR allows a call to `rewriteMaps()` to fail on maps that do not exist in a program. This is required when you try to clone a program that does not use all the maps in the manager `collection`.
Fix CloneProgram for programs that do not use all the maps of a manager.
> Fix Manager.CloneProgram

- probe.go
This PR introduces a new method: `probe.IsTCCLSActive()`
This method returns true if an eBPF TC classifier is active, and false if it is not.
This method is helpful to determine if an interface is being monitored.
> [tc] Check if an eBPF TC classifier is active

- probe.go
Use kprobe events ABI is max active > 0
Currenlty the perf event ABI doesn't allow
to specify a value for max active kprobe
> Use kprobe events ABI is max active > 0

- syscalls.go
> Fix the error type

- manager.go
Fix support for shared (rewritten) maps
> Fix support for shared maps

- manager.go
- probe.go
This PR fixes the `CopyProgram` argument of a probe. Its only use case is when it is used before a call to `manager.Init` is made. It will indicate that during the process of loading the elf file, the `ProgramSpec` structure of the relevant `Probe` will be copied. That's it. The required lookup function were also updated.
Fix the `CopyProgram` feature, which currently breaks the `ConstantEdition` feature for programs that are copied before the manager is initialized.
> [CopyProgram] Fix the usage of CopyProgram

- manager.go
This PR ensures that the state of the manager is reset to `reset` if the initialization failed.
When the initialisation fails (because of the verifier for example), the state of the manager is currently set to `initialized` even though it is not and the `Manager.collection` attribute might be null. Calling `Close()` after a failed initialisation will cause a panic as the manager will try to call `manager.collection.Clos()`.
> [manager] Reset manager state if init failed

- err.go
- probe.go
> Fix unbounded retry and slowdowns

- probe.go
This PR ensures we use the proper parent handle to lookup TC filters on cleanup.
The last PR that fixed TC classifiers messed up the cleanup.
> [TC classifiers] Fix TC classifier cleanup

- go.mod
- go.sum
- manager.go
- ringbuffer.go
> Add support for ring buffers

- go.mod
- go.sum
- perf.go
> make use of readinto

- perf.go
Fix a crash where we were not using the the right `perf.Record` object for a lost samples record when `RecordGetter` is 
or `DataHandler` is not `nil`. This would cause the data handlers to be called with nil data instead of the lost handler.
Crashes like
```
panic: runtime error: index out of range [0] with length 0
goroutine 231 [running]:
github.com/DataDog/datadog-agent/pkg/network/ebpf.ToBatch(...)
/go/src/github.com/DataDog/datadog-agent/pkg/network/ebpf/kprobe.go:86
github.com/DataDog/datadog-agent/pkg/network/tracer/connection/kprobe.(*tcpCloseConsumer).Start.func1()
/go/src/github.com/DataDog/datadog-agent/pkg/network/tracer/connection/kprobe/tcp_close_consumer.go:112 +0x6cd
created by github.com/DataDog/datadog-agent/pkg/network/tracer/connection/kprobe.(*tcpCloseConsumer).Start …
```
> Use same record object for lost and raw samples

- manager.go
This PR adds a new field to the constant editor structure so that we can use both BTF based and legacy constants.
> [constants] Allow using multiple constants types

- examples/activated_probes/Makefile
- examples/clone_vs_add_hook/Makefile
- examples/map_rewrite_vs_map_router/Makefile
- examples/mapspec_editor/Makefile
- examples/object_pinning/Makefile
- examples/program_router/Makefile
- examples/programs/cgroup/Makefile
- examples/programs/kprobe/Makefile
- examples/programs/lsm/Makefile
- examples/programs/lsm/probe.go
- examples/programs/perf_event/Makefile
- examples/programs/socket/Makefile
- examples/programs/tc/Makefile
- examples/programs/tracepoint/Makefile
- examples/programs/uprobe/Makefile
- examples/programs/xdp/Makefile
- examples/tests_and_benchmarks/Makefile
- go.mod
- go.sum
- syscalls.go
Fix LSM programs by adding padding to `bpfRawTracepointOpenAttr`.
> [CWS] Fix lsm programs

- .golangci.yml
- editor.go
- editor_test.go
- map.go
> Fix golangci-lint issues

- go.mod
- go.sum
Agent PR for build example https://github.com/DataDog/datadog-agent/pull/13554
> Bump cilium/ebpf to v0.9.1

- probe.go
This PR hides the clsact qdisc deletion behind a configuration of `Probe`. The rational is that there could be a race between the time we list the existing filter and the time we decide to delete the clsact qdisc. When the race is triggered, we may delete the qdisc eventhough a third party program could have already loaded its programs.
Make sure the manager behaves better with third party programs.
Start the TC example, stop it and then check if the clsact qdisc is still on the interface that was hooked.
> [TC] Do not cleanup qdisc on probe stop

- .github/workflows/build-examples.yml
- examples/program_router/Makefile
> Add github actions to ensure examples are still building

- .github/workflows/lint.yml
- .golangci.yml
- editor_test.go
- manager.go
- perf.go
- ringbuffer.go
- utils.go
Updates to go version and linter version used. Fixes a few minor highlighted issues.
I noticed the Go version was using `1.15`
> Update lint workflow

- manager.go
This PR adds an option to keep the Kernel types so that CloneProgram can still work. This PR doesn't change the current default state of the manager.
Fix CloneProgram usage with BTF.
> [Manager] Add KeepKernelBTF option

- probe.go
Add support for raw_tracepoint probes.
> Add helpers to attach/detach raw_tracepoint probes

- manager.go
> Manager Pause,Resume,Stop must be called under Write lock

- probe.go
Updates `state` checks for `Probe` objects to handle the addition of the `paused` state.
calling `Stop` on a probe would only attempt detach if the state was `running`. A `paused` probe is also valid to detach, so we need to update the state checks.
> Fix state check issues caused by adding paused state

- manager.go
This PR introduces a new parameter to the manager `MapEditorsIgnoreMissingMaps`. This parameter is useful when you want to edit the maps of a new manager with the maps of an old manager without knowing in advance which maps in the old manager are in the new manager.
This is necessary for a CWS feature in the Datadog agent: we're introducing a new manager for a new feature and need to reuse and share existing maps of our current manager.
> Ignore missing maps while editing maps

- go.mod
- go.sum
- manager.go
- manager_test.go
Escapes regex before compilation, to avoid special characters that might exist in the UID set
Bug found in the agent
> escape regexp pattern

- manager.go
- perf.go
- ringbuffer.go
- utils.go
> Add a way to stop readers separately

- manager.go
Removes `ConstantEditors` from options that are probe-specific and only point to excluded functions.
CI errors in datadog-agent for NPM
> remove constant editors for excluded funcs

- examples/constant_editor/main.go
- examples/constant_editor/utils.go
Fix constant editor example
`logrus` was removed.
> Fix constant editor example

- editor.go
- examples/clone_vs_add_hook/main.go
- manager.go
- probe.go
- utils.go
Fix minor lint issues
Cleaner code
> Fix minor lint issues

- go.mod
- go.sum
Updates cilium/ebpf to `0.12.3`
> update cilium/ebpf to 0.12.3

- perfmap.go
- ringbuffer.go
- Expose `BufferSize` from perf map / ring buffer
- Add `RecordHandler` and `RecordGetter` to ring buffer for performance optimized usage
> Expose BufferSize, Add `RecordHandler` and `RecordGetter` to ring buffer

- manager.go
Add `GetProgramSpecs` to manager
We need a way to get all the program specs, including programs that are not listed in `Probes` and may only be tail-called.
> Add GetProgramSpecs

- .github/workflows/ci.yml
- go.mod
- go.sum
require Go 1.21
1.20 is no longer supported
> require Go 1.21

- .github/workflows/ci.yml
- go.mod
- manager.go
use stdlib maps and slices
added in go 1.21
> use stdlib maps and slices

- manager.go
Adds a callback function option for kernel module BTF. It will try to load from default locations first, and then call the callback function if supplied and necessary.
If a callback function is not supplied, kernel module BTF can still be used (if needed) if already provided or is available at the default location.
> Add kernel module CO-RE support

- uprobe.go
Fix the error of the binary file dynamic symbols resolution.
> Fix symbols resolution error

- manager.go
> Provide API for getting all map specs

- manager.go
Fixes bypass instructions to ensure `r0 = 0` before calling `return`.
fentry/fexit programs are strict about the return code
> ensure r0 is 0 before return

- .github/workflows/ci.yml
- go.mod
updates tested and supported Go versions to 1.22 and 1.23
> update supported go versions

- tracefs.go
As reported in https://lore.kernel.org/all/20221121081103.3070449-1-zhengyejian1@huawei.com/T/, a race in the tracefs can cause some kernel crashes. We can't protect against other processes racing with us, but we can at least protect against racing with ourselves and this is what this PR is doing protecting tracefs access with a lock.
> protect tracefs access with a mutex

- manager.go
The current `InitWithOptions` method of the manager is too big causing some strange pattern around:
- unlocking the stateLock
- resetting the state in the second part
This PR splits the method in 2 separate functions allowing to use regular defer for the lock, and one single point for error handling.
> split manager `InitWithOptions` to simplify lock and reset
