DataDog/ebpf-manager

editor.go, err.go, examples/activated_probes/utils.go, examples/clone_vs_add_hook/utils.go, examples/map_rewrite_vs_map_router/demo.go, examples/map_rewrite_vs_map_router/utils.go, examples/mapspec_editor/utils.go, examples/object_pinning/utils.go, examples/program_router/utils.go, examples/programs/cgroup/utils.go, examples/programs/kprobe/utils.go, examples/programs/lsm/utils.go, examples/programs/socket/utils.go, examples/programs/tc/utils.go, examples/programs/tracepoint/utils.go, examples/programs/uprobe/utils.go, examples/programs/xdp/utils.go, examples/tests_and_benchmarks/utils.go, go.mod, go.sum, manager.go, map.go, perf.go, probe.go, selectors.go, syscalls.go, utils.go
Use `errors` and `fmt.Errorf` instead of `github.com/pkg/errors`
Use stdlib where possible
based on branch for #2
=> Use errors and fmt.Errorf instead of github.com/pkg/errors

err.go, go.mod, go.sum, manager.go, probe.go, syscalls.go, utils.go
This PR implements the new perf_event_open ABI to attach kprobes and uprobes (for 4.17+ kernels).
On some recent distributions (and container optimized OS like Bottlerocket), the debug filesystem isn't necessarily mounted and writable. With this PR, the manager will now use the new kernel ABI first, and fallback to the legacy "kprobe_events" method if the new ABI is not available.
This change can be tested by making sure that the examples in this repository are running. We also ran the entire CI on system-probe in the Datadog agent repository.
=> [kprobe/uprobe] Implement perf_event_open ABI to attach kprobes and uprobes

probe.go
This PR fixes a small typo in the `Probe.Copy()` method. If we don't copy the section name, the newly created probe can't be inserted as is in the manager.
Fix a bug in the library.
=> Fix Probe copy

manager.go, probe.go
This PR fixes a small bug that triggers a panic when you declare a `Probe` for a program that you're going to call through a tail call.
=> Fix tail call with declared but not activated programs

examples/activated_probes/main.go, manager.go, utils.go
This PR does 2 things:
- This PR fixes the `ExcludedSections` feature which currently doesn't work, due to the probe selection mechanism from Cilium. The fix implies moving to `ExcludedFunctions`, which means that we cannot exclude entire sections anymore, we have to exclude eBPF programs by their function names.
- This PR ensures that non running probes are started if they are listed in the selector provided to `UpdateActivatedProbes()`.
When the manager fails to start, some probes might be enabled but not running. This means that they will fail validation if `UpdateActivatedProbes` doesn't restart them.
=> Fix the `ExcludedSections` feature and start non running probes on activated list update

probe.go, syscalls.go
It is possible to request that a Uprobe be triggered for only one specific process. Instead of triggering on all instances of the binary, you can specify the `pid` of the traced process in `Probe.PerfEventPID`.
Improve the performance of a Uprobe to reduce the impact of Uprobes on the system.
=> [uprobe] Enable uprobe pid filtering

manager.go, perf.go
This PR fixes 2 deadlocks in the manager that may happen when you try to update the list of activated probes, with a list of probes that contains a validator error, after pausing an active perf map. The manager will try to lock the manager state twice (because of `m.Stop()`), and even if you call `m.stop()`, it will deadlock while waiting for the manager wait group, because the perf map is in `pause` state, which is below `running`, which means that you won't close the perf reader ... which will never release the perf map goroutine ... which will never call `Done()` on the manager waitgroup ...
Fix 2 deadlocks.
=> [UpdateActivatedList] fix update activated list deadlock

manager.go, probe.go
While updating the list of activated probes, some `ProbesSelector` might select probes that are not available on the current host. Instead of returning an error when we call `probe.Attach()` on these probes, rely on the new `ActivatedProbes` list to return an error only when needed.
Fix support for kernels that do not support all the probes during a reload.
=> [UpdateActivatedList] Do not return error on probe Attach error, use activated list

err.go, examples/program_router/main.go, examples/programs/tc/main.go, examples/programs/tc/probe.go, examples/programs/xdp/main.go, go.mod, manager.go, probe.go, utils.go
This PR ensures that the manager plays well with other services that might be using the `clsact` qdisc. The point here is to make sure that it won't touch any BPF filters that don't need to be touched, as well as perform a proper cleanup on start up if a previous manager was abruptly killed.
This PR cleans up the netlink socket cache to prevent leaking network namespaces. Important comments were added when actions are expected from the user of the manager.
```golang
type Probe struct {
[...]
// IfIndexNetns - (TC Classifier & XDP) Network namespace in which the network interface lives. If this value is
// provided, then IfIndexNetnsID is required too.
// WARNING: it is up to the caller of "Probe.Start()" to close this netns handle. Failing to close this handle may
// lead to leaking the …
```
=> [TC classifier][XDP] Make sure the manager plays well with other services that might be using the clsact qdisc

examples/programs/kprobe/ebpf/main.c, examples/programs/kprobe/main.go, manager.go, probe.go, utils.go
This PR ensures that when we resolve the PID of the manager, we start by looking at the host proc filesystem in order to resolve the PID of the current task in the context of the root PID namespace (instead of the container PID namespace in which the manager might be running). This PR expects the host /proc filesystem to be mounted at a directory specified in $HOST_PROC. This follows the deployment convention of the Datadog Agent.
We currently use the namespaced PID to write events in `kprobe_events` and TC BPF filter names. This means that we won't be able to correctly detect if two Datadog Agents are running simultaneously: the last agent to start will never be able to resolve the PID of the first Datadog Agent, and will therefore always try to remove the hook points of the first …
=> [Probe.attachPID] Fix process PID namespace bug

go.mod, probe.go
This PR fixes the returned error when an interface couldn't be resolved.
Return the correct error when a program couldn't be loaded because an interface wasn't found.
=> [resolveLink] return the correct error if the link is not resolved

probe.go
This PR exposes the `ResolveLink` method of `Probe`. This is useful to retrieve the interface on which a probe is attached, without having to resolve it again from its namespace and ifindex.
This is required for a feature in the datadog-agent.
=> [link] Expose the interface on which a probe is attached

err.go, examples/object_pinning/main.go, manager.go, map.go, probe.go, selectors.go
This PR fixes multiple races that occurs when the manager is modified at runtime by different goroutines. For example, if 2 goroutines try to attach and detach a hook point at the same time, the following race may happen:
```
WARNING: DATA RACE
Read at 0x00c0004f64d8 by goroutine 71:
github.com/DataDog/ebpf-manager.(*Manager).stop()
/go/pkg/mod/github.com/!data!dog/ebpf-manager@v0.0.0-20220218133217-a77b0591856e/manager.go:698 +0x210
github.com/DataDog/ebpf-manager.(*Manager).Stop()
/go/pkg/mod/github.com/!data!dog/ebpf-manager@v0.0.0-20220218133217-a77b0591856e/manager.go:684 +0x12d
github.com/DataDog/datadog-agent/pkg/security/probe.(*Probe).Close()
/go/src/github.com/DataDog/datadog-agent/pkg/security/probe/probe.go:954 +0x77
github.com/DataDog/datadog-agent/pkg/security/module.(*Module …
```
=> [manager] Fix multiple races when programs are attached or detached at runtime

err.go, probe.go
This PR ensures that all TC classifiers are loaded on the `clsact` qdisc by hardcoding the parent handle.
After messing up a tiny little configuration of a manager in the Datadog Agent, we eventually started a TC classifier probe with `p.NetworkDirection = 0`. This lead to a drop in network connectivity on the host (on most interfaces). Deleting the `clsact` qdisc (on the impacted interfaces) didn't change anything, and only a restart of the agent made the interfaces recover.
A few hours of debugging later, here is what happened:
- by default, most interfaces default to a `fq_codel` for their root qdisc.
- when trying to load a TC classifier with a `0` as parent handle, [the kernel defaults](https://github.com/torvalds/linux/blob/ed4643521e6af8ab8ed1e467630a85884d2696cf/net/sched/cls_api.c …
=> [TC classifiers] Prevent attaching TC with an empty parent

editor_test.go, examples/clone_vs_add_hook/main.go, go.mod, go.sum, manager.go, probe.go, utils.go
This PR cleans up unused fields of ProgramSpec instances when they're not needed anymore to free up memory.
Reduce the memory impact of the manager at runtime.
=> [memory] Cleanup program spec

manager.go
This PR removes internal TC probes on network namespace flush. This ensures that we do not keep unused probes in the manager. It also ignores unnecessary probe "Init" errors so that they can be handled gracefully by the probe selector interface.
Help mitigate and prevent a race condition in the Datadog Agent during a reload.
=> [manager] delete internal TC probes on network namespace flush

probe.go
This PR mitigates an edge case where we might delete a TC filter that we do not own anymore if a third party stole the handle that the kernel gave us in the first place. There is by design a race when it comes to deleting a TC filter (nothing guarantees that we haven't been replaced), but this PR improves the situation ... a bit.
=> [TC] TC filter lazy deletion

examples/programs/tc/main.go, probe.go
This PR introduces a new attribute to the `Probe` structure: `TCFilterHandle`. This new attribute can be used to manually set the handle that the kernel should use for the bpf filter.
Allow the user to decide which filter to use.
Run the TC example in `/examples/programs/tc` and make sure the loaded TC filter on ingress holds handle `0x2`.
=> [TC] make the handle of a TC filter configurable

manager.go, selectors.go
Exporting RunValidator method of the selectors.
Adding uprobes in `datadog-agent` repository, and some of the uprobes might not exists (depending on the version of `openssl`). I want to use "BestEffort" selector on the "might be missing" uprobes, and "AllOf" selector on the rest.
I want to validate the hooks are properly set, to do so I need to use `RunValidator`.
Since those are uprobes, and I'm hooking `openssl` libraries, it must dynamic per process and during runtime (instead of setting the hooks during load time.
=> selectors: Export RunValidator

manager.go, probe.go
This PR adds `DefaultKprobeAttachMethod` to the manager options. When a `Probe` doesn't have an attach method explicitly configured, it will default to the manager value or `AttachKprobeWithPerfEventOpen` if the probe doesn't have a manager.
This new default value can be used to globally set the attach method of all the probes of a manager, instead of having to manually set it for all the probes.
The kprobe example can be used to check the manager parameter.
=> [Probe] Introduce manager level attach method

.github/workflows/build-examples.yml, examples/programs/fentry/.gitignore, examples/programs/fentry/Makefile, examples/programs/fentry/ebpf/main.c, examples/programs/fentry/main.go, examples/programs/fentry/utils.go, probe.go
Adds helpers to attach/detach probes of type `ebpf.Tracing`.
fentry/fexit port of network tracer
=> Add helpers to attach/detach tracing probes

editor.go, editor_test.go, manager.go, map.go, perf.go, probe.go, ringbuffer.go, syscalls.go, utils.go, utils_test.go
Un-exports several functions and types.
I think most of these were not intended to be used by consumers of the library. Some are currently unused, and can be exported again under a more intentional API.
This may not be exhaustive, but is a good start.
=> Unexport several functions and types

examples/tests_and_benchmarks/main.go
The program does `2 * x`, so it should use an input of `64` if it expects `128`.
failing output:
```
INFO[0000] Running tests ...
INFO[0000] { Input:2 Output:4 } - PASS
INFO[0000] { Input:10 Output:20 } - PASS
INFO[0000] { Input:42 Output:128 } - FAIL (checkout /sys/kernel/debug/tracing/trace_pipe to see the logs)
INFO[0000] { Input:42 Output:84 } - PASS
INFO[0000] Running benchmark ...
INFO[0000] { Input:2 Output:4 } - PASS (duration: 7ns)
INFO[0000] { Input:10 Output:20 } - PASS (duration: 7ns)
INFO[0000] { Input:42 Output:128 } - benchmark FAILED (checkout /sys/kernel/debug/tracing/trace_pipe to see the logs)
INFO[0000] { Input:42 Output:84 } - PASS (duration: 7ns)
```
=> Fix tests-and-benchmarks example

examples/activated_probes/Makefile, examples/clone_vs_add_hook/Makefile, examples/instruction_patching/Makefile, examples/map_rewrite_vs_map_router/Makefile, examples/mapspec_editor/Makefile, examples/object_pinning/Makefile, examples/program_router/Makefile, examples/programs/cgroup/Makefile, examples/programs/fentry/Makefile, examples/programs/kprobe/Makefile, examples/programs/lsm/Makefile, examples/programs/perf_event/Makefile, examples/programs/socket/Makefile, examples/programs/tc/Makefile, examples/programs/tracepoint/Makefile, examples/programs/uprobe/Makefile, examples/programs/xdp/Makefile, examples/tests_and_benchmarks/Makefile
Allow override of `ARCH` in Makefiles
Support arm64
You have to specify `ARCH=arm64` on the command line, but it works at least.
=> update Makefiles to support multiple architectures

examples/programs/cgroup/main.go, probe.go
Fixes cgroup path detection in example
Broken on ubuntu 22.04
=> Fix cgroup example on ubuntu 22.04

go.mod, utils.go
This PR:
- Bump to go 1.18 since we bumped the Datadog Agent to go 1.18
- Fixes the stack trace below which started appearing on master since we stopped exporting some structures (don't ask why I have no idea). Regardless of why the stack trace started appearing, we use to set an invalid finalizer.
On my setup, main is currently broken. See the stack trace below:
```
fatal error: runtime.SetFinalizer: cannot pass *manager.fd to finalizer func() error
goroutine 1 [running]:
runtime.throw({0xc0001a4230?, 0x770668?})
/home/will/.gimme/versions/go1.18.linux.amd64/src/runtime/panic.go:992 +0x71 fp=0xc0001e75b8 sp=0xc0001e7588 pc=0x434df1
runtime.SetFinalizer({0x71a140, 0xc00002a2d0}, {0x6f2b60, 0xc000020100})
/home/will/.gimme/versions/go1.18.linux.amd64/src/runtime/mfinal.go:399 +0x48e …
```
=> [Bug] Fix SetFinalizer stack trace and bump to go 1.18

examples/activated_probes/main.go, examples/clone_vs_add_hook/demo.go, examples/clone_vs_add_hook/main.go, examples/instruction_patching/main.go, examples/map_rewrite_vs_map_router/main.go, examples/object_pinning/main.go, examples/program_router/demo.go, examples/program_router/main.go, examples/programs/cgroup/main.go, examples/programs/fentry/main.go, examples/programs/kprobe/main.go, examples/programs/lsm/main.go, examples/programs/perf_event/main.go, examples/programs/socket/main.go, examples/programs/tc/main.go, examples/programs/tracepoint/main.go, examples/programs/uprobe/main.go, examples/programs/xdp/main.go, examples/tests_and_benchmarks/main.go, manager.go, probe.go
Deprecates `EBPFSection` from `ProbeIdentificationPair` because `EBPFFuncName` is sufficient and we can obtain the section from `Probe.programSpec.SectionName`
Simpler API
=> Deprecate EBPFSection from ProbeIdentificationPair

err.go, manager.go
This PR adds a check in `editMapSpecs` for missing EditorFlags, providing users of ebpf-manager with a useful error message if so.
Wanted to use a mapSpecEdit for a map to work (e.g changing a map size to a non-zero value), but forgot the flags, causing an `invalid argument` error that left me confused, as I thought I was changing the specs correctly. With this change, ebpf-manager should tell the developer, that they need to provide flags for it to work.
=> Add check for missing editor flags in mapSpecEditor

manager.go, probe.go
Since `EBPFSection` is only deprecated but still there, library user can still pass ProbeIdentificationPair containing sections. This can cause issue if the matching is done using OOTB equality (like in a map access for example). This was the case in `UpdateActivatedProbes` causing issue with CWS probe reloading.
This PR also re-enables the display of `EBPFSection` in the `String()` function for probe identification pair since it can cause issues during debugging (you think there is no section, but it's actually false)
=> fix `UpdatedActivatedProbes` with potential sections

manager.go, selectors.go
Here a stack trace
```
[5.15.57-30.131.amzn2022.x86_64][d] WARNING: DATA RACE
[5.15.57-30.131.amzn2022.x86_64][d] Write at 0x00c0009bc380 by goroutine 932:
[5.15.57-30.131.amzn2022.x86_64][d] github.com/DataDog/ebpf-manager.(*Manager).CloneProgram()
[5.15.57-30.131.amzn2022.x86_64][d] /go/pkg/mod/github.com/!data!dog/ebpf-manager@v0.2.0/manager.go:1129 +0x13e4
[5.15.57-30.131.amzn2022.x86_64][d] github.com/DataDog/datadog-agent/pkg/security/probe/resolvers.(*TCResolver).SetupNewTCClassifierWithNetNSHandle()
[5.15.57-30.131.amzn2022.x86_64][d] /go/src/github.com/DataDog/datadog-agent/pkg/security/probe/resolvers/tc_resolver.go:109 +0x6bd
[5.15.57-30.131.amzn2022.x86_64][d] github.com/DataDog/datadog-agent/pkg/security/probe.(*NamespaceResolver).snapshotNetworkDevices() …
```
=> fix data race between selectors and manager

manager.go, probe.go
This PR splits the netlink socket cache from the manager, allowing the probe to not link to the manager but only it's cache. Moreover, this new cache has its own lock allowing the probe to use the cache without locking the whole manager.
Agent test PR: https://github.com/DataDog/datadog-agent/pull/15414
=> extract netlink socket cache from manager

manager.go, manager_test.go, probe.go
If a verifier error is encountered on load, we output the full log in the error string rather than only 1-2 lines. We keep the abbreviated version in the first line as `%w` to allow consumers to unwrap the error if desired.
=> Expose full verifier log on error

manager.go, probe.go
Fix wrong export of internal cache added in https://github.com/DataDog/ebpf-manager/pull/88
=> unexport netlink socket cache

utils.go
The tracefs should be mounted at `/sys/kernel/tracing`, and/or `/sys/kernel/debug/tracing`, or not mounted at all.
Today ebpf-manager rely only on `/sys/kernel/debug/tracing`.
This PR will check first tracefs at `/sys/kernel/tracing` (which should be the default one since kernel 4.1, based on what I understand from [the documentation](https://www.kernel.org/doc/Documentation/trace/ftrace.txt)) and then fallback on `/sys/kernel/debug/tracing`.
=> Also check default tracefs mount point

manager.go, probe.go, syscalls.go
Adds `Pause()` and `Resume()` functions to probes and the manager. Currently supports kprobes, socket filters, and tracepoints.
This allows us to pause and resume eBPF functionality without destroying/re-creating the manager which can take a (relatively) long time. This is primarily motivated by tests.
This does not clear any state from eBPF maps.
Tested with the datadog-agent.
=> Add ability to pause/resume probes

tracefs/tracefs.go, utils.go
Detects whether to use `/sys/kernel/tracing` or `/sys/kernel/debug/tracing` once and caches the result.
Simpler and more efficient usage of mount path.
=> Detect tracefs/debugfs availability once

manager.go
This flag is useful when trying to edit a map from one type to another: you might also need to change its key size / key value. You can also edit the BTF type of the key and the value.
This is needed by CWS to properly handle choosing between a perf ring buffer and a ringbuffer at runtime depending on the machine.
=> Add EditKeyValue flag in map spec editor

manager.go
This PR exports the list of internal eBPF maps from the `Collection` attribute of a `manager`.
The CWS agent needs to be able to list its underlying maps that are in use at runtime for 2 use cases:
- making sure that all maps are shared between its multiple managers
- listing the maps names in use at runtime, this will soon be needed in order to write CWS rules to protect the agent itself
=> Export eBPF maps from the `Collection` of a manager

selectors.go
This PR adds support to a nil `*ProbeSelector`, it's basically something that will amount to 0 probes and will always validate successfully.
This allows function to return `*ProbeSelector` and use it directly, most useful in arrays literal:
```
func f(n string) *ProbeSelector
a := []*ProbeSelector {
f("b"),
f("c"),
}
```
=> make nil `*ProbeSelector` a first class citizen

manager.go, probe.go
Adds an equivalent option to uprobes for choosing the attachment method, as kprobes already have.
=> Add uprobe attach method option

go.mod, manager.go
Adds `GetPrograms()` to manager.
Like `GetMaps()`, I needed a way to get all the loaded eBPF programs. Iterating through `Probes` does not include the tail-called programs.
=> Add GetPrograms

probe.go
Exposes the system ID via a new function `ID()`.
The ID is valuable when iterating over ebpf programs, and it saves a syscall since the manager already knows the correct value.
=> expose ebpf program ID

manager.go
The `ProgramSpec` for `ExcludedFunctions` are deleted when initializing.
However, `GetProgramSpec` does not account for this and returns nil values.
This can cause panic on other control flows.
For example when constant patching with targeted `ProbeIdentificationPairs`  we run into a panic because `GetProgramSpec` returns nil values.
=> Omit excluded `Probes` when listing `ProgramSpecs`

examples/Makefile.ebpf, manager.go, probe.go
Removes `Probe` and `Map` entries for excluded items.
Enables sane usage of those slices in the manager without worrying about nonexistent programs.
=> remove probes/maps for excluded items

manager.go
The goal of this PR is to allow to exclude functions dynamically, for example based on some presence in `/proc/kallsyms`, in some `btf` code or other.
To allow this, this PR adds a new option field for the manager pointing to a stateful excluder that can register new excluded functions at init time. This PR also ensures that excluded probes are not attached/init when updating activated probes.
=> add stateful dynamic function excluder

manager.go
Add `SkipPerfMapReaderStartup` and `SkipRingbufferReaderStartup` options.
The manager's `Start()` function handles both attaching eBPF programs and starting goroutines that read events from perf and ringbuffer maps. Adding these options makes it possible to decouple the two and start reading events after the manager has been started.
=> add an option to skip starting perf/ringbuffer goroutines

examples/constant_editor/ebpf/main.c
Fix missing include in constant_editor
=> Fix missing include in constant_editor

manager.go, probe.go, selectors.go
Remove deprecated `EBPFSection` and make `ProbeIdentificationPair` comparable
Simpler code
API change by removing `Matches` and `EBPFDefinitionMatches`. Will bump to next minor (0.3) on next release.
=> Remove EBPFSection and make ProbeIdentificationPair comparable

manager.go, map.go, probe.go, utils.go
Use `errors.Join` instead of `concatErrors`
Better handling of unwrapping the individual errors.
=> Use errors.Join instead of concatErrors

probe.go, syscalls.go
Use `unix.IoctlSetInt` where appropriate
better type safety
=> Use unix.IoctlSetInt where appropriate

cgroup.go, probe.go, syscalls.go
Use link for cgroup attach/detach
=> Use link for cgroup attach/detach

probe.go, raw_tp.go
=> Use link for raw tracepoint

probe.go, tracing.go
=> Use link for tracing programs

lsm.go, probe.go, syscalls.go
=> Use link for LSM

probe.go, xdp.go
=> Use link for XDP

utils.go, utils_test.go
The function `GetSyscallFnName` currently needs to read the whole kallsyms in memory. This PR changes this to just stream the file line by line.
=> ensure we do not read the whole kallsyms file in memory

utils.go, utils_test.go
Uses a pointer to the slice entry, so it will be mutated, rather than a copy.
Fix #145
=> Use reference to ensure slice entry is mutated

examples/object_pinning/main.go, manager.go, map.go, perf.go, probe.go, ringbuffer.go
Removes deprecated usage of `CollectionSpec.RewriteMaps` and uses `CollectionOptions.MapReplacements` instead.
`MapReplacements`  returns a cloned reference to the `*ebpf.Map` upon collection load. This allows us to get rid of the external/editing flags and tracking, because there is no danger of destructive operations upon `Close`. Pinned maps managed by the manager are detected and handled by the `array` field already being populated.
I split out the loading functions for maps/perfmap/ringbuffer to get rid of the mutex copy.
Remove deprecated usage of `CollectionSpec.RewriteMaps`.
This has a couple of API changes, so requires a version bump. 
`map_rewrite_vs_map_router` example was tested and is still working.
=> Use `CollectionOptions.MapReplacements` for map editing

manager.go, tracefs/tracefs.go, utils.go, utils_test.go
This PR improves the memory profile of the un-cached `FindFilterFunction`:
- removing useless splits and sort
- switching to line-by-line reading of the file (allowing us to only keep a copy of the interesting string and not the whole buffer at once)
and removes the cache completely, because it caches a lot of entries even though the usage of it is pretty low (around 60000 entries, when the system probe only uses this for 2 hooks). Removing the cache is not an issue in itself because `available_filter_functions` is not a regular file, so no real IO there.
Here is a profile showing the gain https://ddstaging.datadoghq.com/profiling/comparison?query=service%3Asystem-probe%20kube_cluster_name%3Astingchameleon%20&compare_end_A=1694707013705&compare_start_A=1694703413705&compareValuesMode=absol …
=> memory improvements for `FindFilterFunction`

manager.go, probe.go
- Calls `Probe.cleanupProgramSpec()` after init, because the program has already been loaded at that point and the instructions are no longer needed.
- Calls `Probe.cleanupProgramSpec()` for `Probe` objects that are not `Enabled`.
Leftover instructions in `ebpf.ProgramSpec` using heap memory. Specifically for tail calls and other Probes that are declared, but not `Enabled` or `Activated`.
https://datadoghq.atlassian.net/browse/EBPF-250
=> cleanup ProgramSpec after init

netlink.go
Calls `Probe.Stop()` before setting the `Probe.Enabled` flag to false. 
This fixes the `CleanupNetworkNamespace` function which was resetting tc Probes instead of detaching them from the corresponding interface. This caused eBPF programs to never be detached from interfaces even after the manager was closed.
=> Fix `CleanupNetworkNamespace` not properly detaching eBPF programs

probe.go
This PR fixes a data race on `systemWideID` triggering when `Probe.Stop()` and `Probe.ID()` are called concurrently.
=> Fix race between `probe.Stop()` and `probe.ID()`

constant_editor.go
Most constant editors are actually "manager wide", meaning that they target all programs under a given manager. Currently when rewriting this kind of constants we iterator over all constant entries, then for each program we create an editor that does the edition. The issue is that creating an editor iterates over all instructions searching for "references", and thus we do a lot of repetitive work (and it's starting to show up in profiles, especially in test profiles were we continuously restart the manager).
To improve this situation this PR reverses the order of iteration for "manager wide" constants by creating an editor only once per program.
Write here in detail how you have tested your changes …
=> optimize "manager wide" constant rewriting

netlink.go
This PR adds the missing lock in `netlinkSocketCache.remove`. This function is not exported and only called from `manager.CleanupNetworkNamespace` which means it's never called with the lock already taken (ensuring this PR is not introducing any deadlock).
Agent PR to test this PR: https://github.com/DataDog/datadog-agent/pull/21053
=> add missing lock in `netlinkSocketCache.remove`

go.mod, go.sum
This release includes kernel module CO-RE support and the fix for the ringbuffer corruption on arm64.
https://github.com/cilium/ebpf/releases/tag/v0.14.0
=> bump `cilium/ebpf` to v0.14.0

kprobe.go, probe.go, tracefs.go, uprobe.go
Fixes uprobes attached via tracefs using the wrong file upon detach.
If uprobes were attached via tracefs, then upon detach they would try to use the `kprobe_events` file. This was because the `GetUProbeType()` function would assign to `p.kprobeType`, which was later used as an indication of if it was a kprobe or uprobe.
=> fix tracefs uprobe detach leak

manager.go, perf_event.go, probe.go, utils.go
Adds `BypassEnabled` config option for the manager, which adds on/off user control of bypassing (early return) eBPF programs. It accomplishes this by injecting some instructions at the beginning of opted-in programs. Opt-in is accomplished by loading a named reference constant.
The actual bypass is controlled via a per-manager array map (per-cpu if supported). Each index corresponds to a unique ebpf program.
The previous `Pause/Resume` functions did not operate as expected.
Testing in the datadog-agent by the existing usage of protocol classification tests.
=> add program bypass support

manager.go, ringbuffer.go
remove unused `RingBufferSize` and `DefaultRingBufferSize`
It had no effect. Ring buffers are sized with `MaxEntries`.
=> remove unused RingBufferSize

err.go, manager.go, state.go
allow user to (optionally) manually load elf before Init
We sometimes need information from the collectionspec to craft the correct options before the manager is initialized. One example is upgrading map types.
=> allow user to manually load elf before Init

manager.go
It can be useful to edit the programspec during a clone operation, especially when managing fentry probes. This PR adds a new method to the manager `CloneProgramWithSpecEditor` extending `CloneProgram` with a callback allowing spec modification.
=> add `CloneProgramWithSpecEditor` allowing to edit the program spec during program copy

probe.go
disable bypass when detaching a probe
Hooks that were detached and later attached could have the wrong bypass state applied.
=> disable bypass when detaching a probe

go.mod, go.sum
fixes a bug when online cpus does not match possible cpus
https://github.com/cilium/ebpf/pull/1503
=> update cilium with perf fix

go.mod, go.sum
https://github.com/cilium/ebpf/commit/63c6cf8fc5b2c94aa755c8ef64fb95e9e3be3d23 removes allocs for error when key is missing
Reduced memory allocations.
=> update ebpf lib to reduce map allocs

examples/mapspec_editor/main.go, manager.go, manager_test.go
This PR uses the eBPF loader library helper for removing the rlimit on locked memory. This helper only removes the limit when eBPF does not account memory to cgroup, which was introduced in the kernel with this [patch](https://lore.kernel.org/bpf/20201201215900.3569844-1-guro@fb.com/t/). Prior to this patch the kernel used rlimit based accounting to calculate how much memory could be used for eBPF maps. For these kernels the loader will set the limit to infinity.
Moreover, since all users of the `RLimit` option set the limit to the max, this option has been changed to a boolean `RemoveRlimit`.
=> Remove Rlimit only when eBPF does not account memory to cgroup

constant_editor.go
This PR adds a new field to the constant editor, allowing to provide a callback to get the value of the constant instead of the direct value.
This is useful for example if you want the value to differ depending on the program.
In the agent, I want a constant to represent the amount of arguments taken by the hooked function. This will allow me to do that.
=> add callback based constant editor

constant_editor.go
`isUnreferencedSymbol` actually allocates some memory, so checking first for `FailOnMissing` allows this check to not allocate in most cases (especially `FailOnMissing` is never used in the agent).
=> check for `FailOnMissing` before the error type check

manager.go, map.go
The map `Freeze` field was removed by the upstream cilium/ebpf lib in https://github.com/cilium/ebpf/pull/1558. This PR removes the support for this field in the ebpf-manager since this field is not used in the agent either.
=> remove support for frozen maps

go.mod, go.sum, manager.go
Modifies the `(*Manager) Close()` method to close the probes concurrently.
The Networks team has dozens of kprobes and each one takes 30-50ms to call the close() syscall on the perf_kprobe PMU, which adds up to an extra second of time on each test. We set up and tear down the tracer entirely for each test, which across all our tests, adds up to minutes of test time.
CI passes here showing KMT was all green: https://github.com/DataDog/datadog-agent/pull/33054
=> Close probes concurrently

netlink.go, tc.go
This PR ensures that the `tcFilterCount` field used in TC probes is thread-safe.
After #212 was introduced, data races were detected when multiple TC probes stopped at the same time.
Tested in datadog-agent CI: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/53780200
=> Make TC filter count thread-safe

constant_editor.go, go.mod, go.sum, manager.go
Updates `cilium/ebpf` to v0.17.1
Also includes a bugfix to kernel module BTF functionality: https://github.com/cilium/ebpf/commit/fd1fe1b9ac2532d2aec6cc70e05e24e305f78f19
=> update cilium/ebpf to v0.17.1

.github/workflows/ci.yml, go.mod
update to go 1.23 and 1.24
1.22 no longer supported
=> update to go 1.23 and 1.24

go.mod, go.sum
Updates `github.com/cilium/ebpf` to https://github.com/cilium/ebpf/commit/0bfb15fb22619206c8c6d54583cc35370813dd80
https://github.com/cilium/ebpf/commit/e439d37e580e2d66e98f2b987f8ba0c295231439 included a bug that prevented the verifier log size from reaching the maximum. This presented as an infinite loop in our CI. See https://github.com/cilium/ebpf/pull/1679 and and https://github.com/cilium/ebpf/pull/1693
=> update cilium with verifier log size fix

kprobe.go, uprobe.go
When attaching a uprobe, by default, we currently first try to attach using PMU and if it fails (for any reason) we fallback on tracefs.
Falling back on tracefs is only needed if the PMU failure is related to it not being supported, if the failure is related to the arguments themselves it doesn't really make sense to fallback on tracefs
This also brings the benefit of limiting the amount of potential failing tracefs calls that can trigger a kernel oops, see https://lore.kernel.org/all/20221121081103.3070449-1-zhengyejian1@huawei.com/T/ for more info.
=> do not try fallback attach method if start returned ErrNotSupported

kprobe.go
This PR adds a method to the `Probe` object for exposing the associated perf event fd if present.
This fd is intended to be used in the agent for triggering stat collection of the perf event.
=> Expose perf event fd
